# Client

* ### Encrypt transaction datapoint
* ### Send to server for inference
* ### Decrypt response

## XGBoost endpoint for ULB dataset

In [1]:
%run client.py --dataset=ulb --model=xgboost

/home/nugentd1@ad.mee.tcd.ie/nuggi/fyp/cc-he-poc/src/env/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
273329,165549.0,-1.00639,1.033489,0.565226,-0.805698,0.692072,-1.241173,1.102883,-0.39798,0.520071,...,0.159672,-0.38203,-0.635888,-0.122017,0.027249,-0.39466,0.130769,0.27721,0.124278,4.49

Expected result: 0

Loading keys from ./client-files/encrypted-ulb-xgboost-keys.pt

Encrypted input:

,T61QIJArhkvP9UHRBiz2jRGmvsh2yL+Ht3/15L/0YRc=,+IqSPvL0uzxn0Yhtsa8MknVMXYf274bUbFsNAKXgHGQ=,5mBdyp/JuwJQLHJDVlDjJwFC2UmBucnoQ6xY3f8NT6E=,CdQZzugFlZs6infmqvxr3FGCD2mF4iMs/edFnyvBFM8=,1FGODYsxe7uUZR1wEU7w52IvI5aM14yMbwwp1SZ60VY=,oGbR1gHp1R3fg7aBn/LwG+Q9lGgywht79rHI0GuanMk=,puG3z+kSHNp84OKsHYbPoUeyLPvHGu9sh9DG/3Mq/Vk=,vUsEs/EEfXJsrYiWZrKhszvALIdxpYzFKrNS5tktHQE=,E0wtdOdaqO9to20bbzbNsD/Mb8Si+5e94hSEO2qD+AI=,k7CXhgcZgkYTu8gRL/8tbuUcO3yX7jllLH7km/6BMIE=,...,eiQc8a0Cfoun0kHXQCFrzezNj1OTFW21GQobplx2iJI=,gC4dmvYUTFam8zpAzhRbI7gFPJr1vcLdJwl13/oi7q4=,vBWdGj+Vh7YMLPB6VKEtUnlLuajCi/n8jvDNKvipB8Y=,UShc7YhNit/IAvaNCDzqfzwjzcF7Ll+9YF+pXndF5hw=,OecIdilUdNP4SMODIApdTKHUK/8z5285PZmF3xTjAlw=,xbFFumgLHYd7Nv1bVlKMsPA0Ea7cRL/b4S4cNzoR9GI=,0efy94YiN4DyZshG05RzZg0rzA+/YKGeopN3L8cKb4I=,gew0xjtmCwsEB2btZFBYh7ChD5sl6lTik1TCvt6gTiw=,G2AMw00T/OH+wJTduoRpKErP6MwKcQz5cVjOE/wzDi0=,Qq8kK5BVhWvhL8VzzSEWWP+Aco+7FG8ryiFAv1EEcRc=
273329,8.837007e+18,6.013598e+15,6.122419e+15,6.097446e+15,6.024304e+15,6.104209e+15,6.001079e+15,6.126123e+15,6.046053e+15,6.095038e+15,...,6.075812e+15,6.046905e+15,6.033360e+15,6.060775e+15,6.068742e+15,6.046231e+15,6.074269e+15,6.082079e+15,6.073923e+15,6.306798e+15

Sending encrypted input to http://134.226.86.101:8000/xgboost/ulb

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7f3376c4cc40>

Decrypted result: 0
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 0 seconds, 312 ms

## Ensuring selected transaction is fraudulant

In [2]:
%run client.py --dataset=ulb --model=xgboost --fraudulant

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
247673,153653.0,-5.192496,3.164721,-5.047679,2.246597,-4.011781,-0.638908,-2.873463,1.576318,-2.861986,...,-1.85047,1.167244,-1.006617,0.774562,0.063397,-0.390658,1.884741,-1.742558,-0.082216,247.86

Expected result: 1

Loading keys from ./client-files/encrypted-ulb-xgboost-keys.pt

Encrypted input:

,T61QIJArhkvP9UHRBiz2jRGmvsh2yL+Ht3/15L/0YRc=,+IqSPvL0uzxn0Yhtsa8MknVMXYf274bUbFsNAKXgHGQ=,5mBdyp/JuwJQLHJDVlDjJwFC2UmBucnoQ6xY3f8NT6E=,CdQZzugFlZs6infmqvxr3FGCD2mF4iMs/edFnyvBFM8=,1FGODYsxe7uUZR1wEU7w52IvI5aM14yMbwwp1SZ60VY=,oGbR1gHp1R3fg7aBn/LwG+Q9lGgywht79rHI0GuanMk=,puG3z+kSHNp84OKsHYbPoUeyLPvHGu9sh9DG/3Mq/Vk=,vUsEs/EEfXJsrYiWZrKhszvALIdxpYzFKrNS5tktHQE=,E0wtdOdaqO9to20bbzbNsD/Mb8Si+5e94hSEO2qD+AI=,k7CXhgcZgkYTu8gRL/8tbuUcO3yX7jllLH7km/6BMIE=,...,eiQc8a0Cfoun0kHXQCFrzezNj1OTFW21GQobplx2iJI=,gC4dmvYUTFam8zpAzhRbI7gFPJr1vcLdJwl13/oi7q4=,vBWdGj+Vh7YMLPB6VKEtUnlLuajCi/n8jvDNKvipB8Y=,UShc7YhNit/IAvaNCDzqfzwjzcF7Ll+9YF+pXndF5hw=,OecIdilUdNP4SMODIApdTKHUK/8z5285PZmF3xTjAlw=,xbFFumgLHYd7Nv1bVlKMsPA0Ea7cRL/b4S4cNzoR9GI=,0efy94YiN4DyZshG05RzZg0rzA+/YKGeopN3L8cKb4I=,gew0xjtmCwsEB2btZFBYh7ChD5sl6lTik1TCvt6gTiw=,G2AMw00T/OH+wJTduoRpKErP6MwKcQz5cVjOE/wzDi0=,Qq8kK5BVhWvhL8VzzSEWWP+Aco+7FG8ryiFAv1EEcRc=
247673,8.202434e+18,5.790313e+15,6.236109e+15,5.798041e+15,6.187127e+15,5.853299e+15,6.033200e+15,5.914010e+15,6.151369e+15,5.914621e+15,...,5.968577e+15,6.129555e+15,6.013586e+15,6.108606e+15,6.070674e+15,6.046444e+15,6.167824e+15,5.974336e+15,6.062902e+15,1.928831e+16

Sending encrypted input to http://134.226.86.101:8000/xgboost/ulb

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7f3376050df0>

Decrypted result: 1
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 0 seconds, 302 ms

## Neural Network endpoint for ULB Dataset

In [3]:
%run client.py --dataset=ulb --model=nn --fraudulant

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
234705,148074.0,-2.219219,0.727831,-5.45823,5.92485,3.932464,-3.085984,-1.67787,0.865075,-3.17726,...,0.964772,0.417472,-0.817343,-0.028752,0.025723,-0.825835,-0.013089,0.413291,-0.131387,0.0

Expected result: 1

Encrypted input:
<tenseal.tensors.ckksvector.CKKSVector object at 0x7f337607fc70>

Sending encrypted input to http://134.226.86.101:8000/nn/ulb

Received encrypted result:
 <tenseal.tensors.ckksvector.CKKSVector object at 0x7f3376c705e0>

Decrypted result: 1
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 4 seconds, 194 ms

## XGBoost endpoint for IEEE dataset

In [4]:
%run client.py --dataset=ieee --model=xgboost --fraudulant

Loading ieee dataset...


Test input:

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
3570446,15606561,151.95,4,6170,174.0,150.0,4,226.0,3,315.0,...,0,-999.0,0,0,0,0,0,0,0,0

Expected result: 1

Loading keys from ./client-files/encrypted-ieee-xgboost-keys.pt

Encrypted input:

,YlqZ/YZUJ4hgcPH0Vz7/prUaD/diEPoXEffcqBXGUDw=,+DwWI1JjYdstvYTpOmP0PP8HpBg8PoQmo7Q6jC5I/m4=,cdAv2Vi06dhelVEGX0OQ+shEOJzQz3GoX+oydLZDyDw=,EGSWQ9soz4NVD8b12BlUhYOd+HsWSpd1R/Ar1P10WEA=,JErRTc1XpfqCHh+MD/FR6KHPUtid72XAsXR8ASMuPx8=,yeurJefUJiwZ1LXNVXOFC2eRQjT+t+mLNfJ0H9jtIsc=,M10bWmmxR8XQmfC7Kt1IDNo+EYuIiM+fdwLnxduVWl4=,Zsx1Xhl1Oxzc2Tzp1zax2NK+ssRGN+LcxiGcrhHpMfk=,DqDWy6s9QHM8yajq3w4z/itmAO0x4DWoTQb9CBvQzCQ=,FaVYCStoNLkLPc7MSumH4wtQtMuKR0hZbfFVGA0weCo=,...,NowUoh2EuULV63kUmHVrt3aWcC0awCVrTh5kUdKGdbA=,8Efbs/VtjSGBjNgq1umRq4LCXB+4T65VBcObNmP8DWA=,hKqxq2wcMYQ9qJ+8eqv17QeCNsERYMEN9UzTmlLXr9A=,J2O9LNdpPU+/eG4N7UUSn58kDp0R4wlNqF9CaGzQCsA=,DDBygamRcjw54YSip8YYYz1+nusc8FuRb7J1sD41Fes=,fKl5HGQLA08WsBpiO2b4aIXo/blHr9Ao6h1XBoqtkfc=,H9mqj/L+07att2bIta5+r6IBwKC6ADno7WNCDc1ioPE=,0yWGvDjCy1zc56O8B2PdH/HNld3L9RGFHYLlW5XQKC8=,2ziFkV4bEmXq4dDGlFdCchvjMzUsUfmgFSQwJxs/uC4=,1PYaJGvNZNkFEDHo5SNnaP9DQ38CRlUTbJPZYeb1eVY=
TransactionID,,,,,,,,,,,,,,,,,,,,,
3570446,9104045350963372082,6.713762e+14,585094480806562,4182121674988643,6.842377e+14,6.702393e+14,585094480806562,7.145735e+14,584511257079968,7.664902e+14,...,582761585030600,41524.0,582761585030600,582761585030600,582761585030600,582761585030600,582761585030600,582761585030600,582761585030600,582761585030600

Sending encrypted input to http://134.226.86.101:8000/xgboost/ieee

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7f3371ed6460>

Decrypted result: 0
Which is incorrect.
Time taken from encryption of input to decryption of result: 0 mins, 2 seconds, 315 ms