# Client Side

* ### Encrypt transaction datapoint
* ### Send to server for inference
* ### Decrypt response

## XGBoost endpoint for ULB dataset

In [3]:
%run client.py --dataset=ulb --model=xgboost

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
268444,163214.0,-1.248321,1.997575,-0.544809,-0.860984,0.529701,-1.190311,1.367489,-0.615384,1.662114,...,1.006743,0.060228,1.223803,-0.118718,-0.082649,-0.49977,-0.236825,0.916828,0.296307,0.79

Expected result: 0

Loading keys from ./client-files/encrypted-ulb-xgboost-keys.pt

Encrypted input:

,qG8cnKlCg3T18240V0wX2LCCyYbOJbZKiT20RT0OnBo=,tef8D2m3ceAz514jKse6bpAZIOgIlylpcGS4KrGsVoE=,DDSPSbmfIj6z80sA8U9ZWgKxhGIZSeq18S837oMg89o=,rzUAqLYPbRREY0D6HcOcj0lIHj71s3uY0++vMcs3eMk=,FxEhh5IjYz6frS2Xj/5aKHPRiXyfHVQdbIEvpD8dDtU=,GZHogpIkCthDxPKxzgVCzk7IjZjEwADK9fLtirVC1qU=,czTsa0QQGK5VJREcYEmS3syHOnaHD4tag+b6iZuPoEQ=,uYSSVaPm/AwczMAS4QKa9zSFr5kDe1PYEhTf+gwdxYk=,IKgOzKTChc462iDLJCO7GmrgGlQNozY+5aBsMpkJDI8=,+mxQchkYHv4eJnl4TrVbQsk3X3OhRtRjz1a96HJZTPc=,...,Tp7I1VnKK9oqbHVcZyWWmehccleQRHISgr0G1GlllY8=,ihYYpXc/sFaz5n7xIP3Uuem4JQ3SyRByFCSJQ1i3N2A=,gCR4QZvfgvc7ygoPzOsfJ1MtC2Pmq/QwS3V7pp6x5lU=,61QPs0cililLcsejjDBpjHY8QsQgNKgJFztelG+jRNY=,NnzZj3kp7AW9gDU73rHrhxLkNyab6Zhj7IN+9sKWCUc=,YU0r8iCKhm9b+Qj2B4f94Ybidg0YWsipqA0v9KELSw0=,GnE/S4DVhwQzN2Siabj29uhbFM7R/DfWAFB69MrEP8o=,XbPktl0WPhPZpj4lYLF3dsxDXmzwKt6ove3AZhqDB/g=,ms2JazVwXKuYglf20DRED46dAh/X04id5orfwrgj9c4=,5C0TeYbj7gY9ae/wA6FtNOnKreF0k6XOvyGeZhneV78=
268444,8.712449e+18,6.000976e+15,6.174140e+15,6.038514e+15,6.021643e+15,6.095831e+15,6.004069e+15,6.140527e+15,6.034746e+15,6.156242e+15,...,6.121281e+15,6.070786e+15,6.132862e+15,6.061243e+15,6.063167e+15,6.040918e+15,6.054938e+15,6.116489e+15,6.083379e+15,6.109721e+15

Sending encrypted input to http://134.226.86.101:8000/xgboost/ulb

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7fe9ed828850>

Decrypted result: 0
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 0 seconds, 274 ms

## Ensuring selected transaction is fraudulant

In [4]:
%run client.py --dataset=ulb --model=xgboost --fraudulant

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
262560,160537.0,0.567539,3.309385,-6.631268,6.394574,-0.054172,-2.396535,-2.792489,0.514811,-3.54178,...,0.555412,0.614221,-0.365047,-0.180409,-0.523271,0.645054,0.246466,0.902675,0.473571,4.69

Expected result: 1

Loading keys from ./client-files/encrypted-ulb-xgboost-keys.pt

Encrypted input:

,qG8cnKlCg3T18240V0wX2LCCyYbOJbZKiT20RT0OnBo=,tef8D2m3ceAz514jKse6bpAZIOgIlylpcGS4KrGsVoE=,DDSPSbmfIj6z80sA8U9ZWgKxhGIZSeq18S837oMg89o=,rzUAqLYPbRREY0D6HcOcj0lIHj71s3uY0++vMcs3eMk=,FxEhh5IjYz6frS2Xj/5aKHPRiXyfHVQdbIEvpD8dDtU=,GZHogpIkCthDxPKxzgVCzk7IjZjEwADK9fLtirVC1qU=,czTsa0QQGK5VJREcYEmS3syHOnaHD4tag+b6iZuPoEQ=,uYSSVaPm/AwczMAS4QKa9zSFr5kDe1PYEhTf+gwdxYk=,IKgOzKTChc462iDLJCO7GmrgGlQNozY+5aBsMpkJDI8=,+mxQchkYHv4eJnl4TrVbQsk3X3OhRtRjz1a96HJZTPc=,...,Tp7I1VnKK9oqbHVcZyWWmehccleQRHISgr0G1GlllY8=,ihYYpXc/sFaz5n7xIP3Uuem4JQ3SyRByFCSJQ1i3N2A=,gCR4QZvfgvc7ygoPzOsfJ1MtC2Pmq/QwS3V7pp6x5lU=,61QPs0cililLcsejjDBpjHY8QsQgNKgJFztelG+jRNY=,NnzZj3kp7AW9gDU73rHrhxLkNyab6Zhj7IN+9sKWCUc=,YU0r8iCKhm9b+Qj2B4f94Ybidg0YWsipqA0v9KELSw0=,GnE/S4DVhwQzN2Siabj29uhbFM7R/DfWAFB69MrEP8o=,XbPktl0WPhPZpj4lYLF3dsxDXmzwKt6ove3AZhqDB/g=,ms2JazVwXKuYglf20DRED46dAh/X04id5orfwrgj9c4=,5C0TeYbj7gY9ae/wA6FtNOnKreF0k6XOvyGeZhneV78=
262560,8.569650e+18,6.097848e+15,6.244103e+15,5.713824e+15,6.408664e+15,6.064687e+15,5.939734e+15,5.918610e+15,6.095038e+15,5.878638e+15,...,6.097201e+15,6.100339e+15,6.048102e+15,6.057949e+15,6.039662e+15,6.101986e+15,6.080720e+15,6.115734e+15,6.092839e+15,6.317743e+15

Sending encrypted input to http://134.226.86.101:8000/xgboost/ulb

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7feaa016cf10>

Decrypted result: 1
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 0 seconds, 265 ms

## Neural Network endpoint for ULB Dataset

In [5]:
%run client.py --dataset=ulb --model=nn --fraudulant

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
254395,156710.0,0.202402,1.17627,0.346379,2.882138,1.407133,-0.504355,1.438537,-0.395603,-1.555142,...,-0.206239,0.24256,0.84123,-0.370157,-0.026012,0.491954,0.234576,-0.279788,-0.331933,7.59

Expected result: 1

Encrypted input:
<tenseal.tensors.ckksvector.CKKSVector object at 0x7fe9e8ae6dc0>

Sending encrypted input to http://134.226.86.101:8000/nn/ulb

Received encrypted result:
 <tenseal.tensors.ckksvector.CKKSVector object at 0x7fe9e8ae6c10>

Decrypted result: 0
Which is incorrect.
Time taken from encryption of input to decryption of result: 0 mins, 3 seconds, 871 ms

## XGBoost endpoint for IEEE dataset

In [6]:
%run client.py --dataset=ieee --model=xgboost --fraudulant

Loading ieee dataset...


Test input:

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
3557572,15136042,500.0,2,16075,514.0,150.0,3,102.0,2,264.0,...,38,32.0,37,4,2,1,2,1,2,1699

Expected result: 1

Loading keys from ./client-files/encrypted-ieee-xgboost-keys.pt

Encrypted input:

,43HEV9dMEh5WMXhD6FL4mRHMHS6ZfolL3dXs9MZMlto=,IASd7mJO4idCcyGc8PAmOFTkKSQawOuvgYSRLaK0mWw=,DyrxEkItlOWSb01tnnzuMjzJuQHrqxrDRVvUDBcGbpA=,Px+XuaTCVoJMvigLRZqI4FWRQGVUFphGKO5HzIUMQcc=,xqQzFcK3xeziXJ07bA7rgXkDti2z8Q1rrZAUWhZDTWg=,D3ZBCWh8kKTmB4HnDeTikQVPYZpduPpTpUUHRm26VTw=,SC8fO8nqc6bialY5yi618OIPse/a1G47gj61rWp1/J0=,7WUt9EEh0andIDMciAZ2GVBBk6Fb5qxk1Xb4gOgyZiw=,jYmaI2XpCvseXCI44nHqgW8jCKj0/XffIXBzCNANyHw=,9btUWAf5tRAXTc3+Jt3ei7AQWl5BlQHOU6+4QYsfdcA=,...,yo+90sVPi4DfHl7jP7RpHEidkiP26YK8uaZAeWrH/TI=,gl8424Xwml93efRxMbTjATe9MNkAgC83WLBNhD1Lr8s=,WI3BSAObvBOIFgMOUgNTQ9fOS7hsyczBUzivwSkXItg=,ft4k+5dDo/M2aZA1JJO+nDPqn+9vZaq8KrmKZlDh//k=,qcLk0lEbCRTGBCYKGblLjamqeVeR4ScFEbOxl/jSWjw=,WNs7MApQbVIHKF1Ey+bM8JaxQ3aEdoNXXLFszKwytvs=,WIZH8hDhwX2zgtVQce25i18GhUJEc2YD11YSdCCk5uI=,LvN6oJOYbWpV4vL3sUJw3X93mSvv/6/YhJguYz5C2f8=,4yqsXT9dLoL4y7ZZZX0BRVyHRpt2OaBFB09Y4L6OQrE=,CdOfJtRjhUprpEQybAKbQ9wsWfCuU6vVCcuLsoGwoyQ=
TransactionID,,,,,,,,,,,,,,,,,,,,,
3557572,8829585730080037046,8.744544e+14,583965031550875,9959517614786820,8.826220e+14,6.703117e+14,584548117171521,6.423064e+14,583965031550875,7.368052e+14,...,604964394503389,6.014699e+14,604381294577426,585132735890681,583965031550875,583383178792765,583965031550875,583383178792765,583965031550875,1573815169613675

Sending encrypted input to http://134.226.86.101:8000/xgboost/ieee

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7fe9e76a1f10>

Decrypted result: 1
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 3 seconds, 722 ms