# Client Side

* Encrypt transaction data
* Send to server for inference
* Decrypt response

## XGBoost endpoint for ULB dataset

In [1]:
%run client.py --dataset=ulb --model=xgboost

/home/nugentd1@ad.mee.tcd.ie/nuggi/fyp/cc-he-poc/src/env/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
244574,152407.0,-1.337483,1.571356,-0.371266,-0.689817,0.334334,-0.145739,0.280048,0.763778,-0.705468,...,-0.315586,-0.0233,-0.547756,-0.061487,0.280098,-0.092835,-0.590468,-0.5523,0.004404,11.85

Expected result: 0

Loading keys from ./client-files/encrypted-ulb-xgboost-keys.pt

Encrypted input:

,czebKLDJQhMNIYeCImYnpT3RpOTNcouhna83GH2EikA=,1LB2u3QUNLqLTGAHE5HhOIRDiEgOmjiOlsxY+pt/x8I=,3fq/Jj+i2e41xCl5D+SKbYQuJQXw/v3/peDD651luGA=,7oI7BRkwRDdFVEP+Y9tyxgYIuvxBfz4wvHEjo2EG/9M=,HGMc39lGxwOOy9gCBzx50qt/9SpJYxpx0BOUe/el0tM=,9z3oMmvj57D+0Oy/Bvbfs+L7uzJpjbnsk9C7oRZdzYM=,z2L/UIssLUJH4EfL4uj7gMYs5gO7IfEjIbU/VEpb1UY=,kFJKFHmWsT5kSVZxir/faVTARRmjXrWCzvMa7pHUCbQ=,AjBvhmjmV0ikU+SjANC1fgzfLLbONa45wI6SVrL6p/M=,4h6MMkxuYTnCIROrC5ezrhvBNC0Rf1uXQvOa3XuJgrg=,...,M4lVuGkM3WTOZ5zb93Xeqv8MNfDTXS/VP7Lff9QQZzQ=,jPQ5DyE+LAHDGa5iBhKBb71gQFwFMbrr25CQcoV835k=,c2rDuxq3lwmeJ9kkPgNi92+r5JvHRMnPvK7xgRd+MEk=,NaPZQwwKMW21sNYnDQ0yhMVJkzbKHqLf+cV9mDozipo=,vpRf3Igmy7gUf2ROngKCFUELOlBhVOK/cA2CUQg6EYI=,AJgpkzqQV1tA+mGNuCKHBMNvGYHowN8whRErDgCElS0=,fvU3zp28b5W8xB9Qwuqsu8jg5Oks+bvhsuyCbrCaA8U=,FlhcjP2mexBn8tuG1tyIMI5Zapjk1VzIA9fWNfMDZp8=,vdJ5Gcm7heE6I6pAHth+J/CXmD0Fj50ILJjWcaQIqJE=,G6e2H9GvGiUiHgfJJhz1CqZDK1yGpX0FSyqS2vgIktw=
244574,8.135967e+18,5.995725e+15,6.150893e+15,6.047262e+15,6.030264e+15,6.084900e+15,6.059293e+15,6.082004e+15,6.107805e+15,6.029430e+15,...,6.050233e+15,6.065823e+15,6.037844e+15,6.063788e+15,6.082007e+15,6.062116e+15,6.035566e+15,6.037602e+15,6.067302e+15,6.699102e+15

Sending encrypted input to http://134.226.86.101:8000/xgboost/ulb

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7f30ce34bf40>

Decrypted result: 0
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 0 seconds, 349 ms

## Ensuring selected transaction is fraudulant

In [3]:
%run client.py --dataset=ulb --model=xgboost --fraudulant

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
244004,152165.0,-4.673231,4.195976,-8.392423,7.743215,-1.138803,-2.094899,-3.839487,0.543053,-1.528448,...,-0.180279,0.554185,0.656076,0.482417,-0.624399,-0.296289,0.374802,-2.678544,0.412368,1.0

Expected result: 1

Loading keys from ./client-files/encrypted-ulb-xgboost-keys.pt

Encrypted input:

,czebKLDJQhMNIYeCImYnpT3RpOTNcouhna83GH2EikA=,1LB2u3QUNLqLTGAHE5HhOIRDiEgOmjiOlsxY+pt/x8I=,3fq/Jj+i2e41xCl5D+SKbYQuJQXw/v3/peDD651luGA=,7oI7BRkwRDdFVEP+Y9tyxgYIuvxBfz4wvHEjo2EG/9M=,HGMc39lGxwOOy9gCBzx50qt/9SpJYxpx0BOUe/el0tM=,9z3oMmvj57D+0Oy/Bvbfs+L7uzJpjbnsk9C7oRZdzYM=,z2L/UIssLUJH4EfL4uj7gMYs5gO7IfEjIbU/VEpb1UY=,kFJKFHmWsT5kSVZxir/faVTARRmjXrWCzvMa7pHUCbQ=,AjBvhmjmV0ikU+SjANC1fgzfLLbONa45wI6SVrL6p/M=,4h6MMkxuYTnCIROrC5ezrhvBNC0Rf1uXQvOa3XuJgrg=,...,M4lVuGkM3WTOZ5zb93Xeqv8MNfDTXS/VP7Lff9QQZzQ=,jPQ5DyE+LAHDGa5iBhKBb71gQFwFMbrr25CQcoV835k=,c2rDuxq3lwmeJ9kkPgNi92+r5JvHRMnPvK7xgRd+MEk=,NaPZQwwKMW21sNYnDQ0yhMVJkzbKHqLf+cV9mDozipo=,vpRf3Igmy7gUf2ROngKCFUELOlBhVOK/cA2CUQg6EYI=,AJgpkzqQV1tA+mGNuCKHBMNvGYHowN8whRErDgCElS0=,fvU3zp28b5W8xB9Qwuqsu8jg5Oks+bvhsuyCbrCaA8U=,FlhcjP2mexBn8tuG1tyIMI5Zapjk1VzIA9fWNfMDZp8=,vdJ5Gcm7heE6I6pAHth+J/CXmD0Fj50ILJjWcaQIqJE=,G6e2H9GvGiUiHgfJJhz1CqZDK1yGpX0FSyqS2vgIktw=
244004,8.123057e+18,5.817793e+15,6.290874e+15,5.619389e+15,6.480072e+15,6.006319e+15,5.955328e+15,5.862269e+15,6.096036e+15,5.985536e+15,...,6.057451e+15,6.096630e+15,6.102058e+15,6.092799e+15,6.033757e+15,6.051262e+15,6.087059e+15,5.924188e+15,6.089064e+15,6.120407e+15

Sending encrypted input to http://134.226.86.101:8000/xgboost/ulb

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7f30cd7430d0>

Decrypted result: 1
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 0 seconds, 315 ms

## Neural Network endpoint for ULB Dataset

In [4]:
%run client.py --dataset=ulb --model=nn --fraudulant

Loading ulb dataset...


Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
276864,167338.0,-1.374424,2.793185,-4.346572,2.400731,-1.688433,0.111136,-0.922038,-2.14993,-2.027474,...,0.650196,-0.870779,0.504849,0.137994,0.368275,0.103137,-0.414209,0.454982,0.096711,349.08

Expected result: 1

Encrypted input:
<tenseal.tensors.ckksvector.CKKSVector object at 0x7f30cd7935e0>

Sending encrypted input to http://134.226.86.101:8000/nn/ulb

Received encrypted result:
 <tenseal.tensors.ckksvector.CKKSVector object at 0x7f3184213be0>

Decrypted result: 1
Which is correct!
Time taken from encryption of input to decryption of result: 0 mins, 3 seconds, 698 ms

## XGBoost endpoint for IEEE dataset

In [5]:
%run client.py --dataset=ieee --model=xgboost --fraudulant

Loading ieee dataset...


Test input:

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
3468513,12515707,6.271,0,15885,545.0,185.0,4,138.0,3,-999.0,...,55,-999.0,0,0,1,1,2,1,2,191

Expected result: 1

Loading keys from ./client-files/encrypted-ieee-xgboost-keys.pt

Encrypted input:

,vyD5ecshrXBqTaDe81E8pEKj2tit198YEHc9T4jIbbY=,fD1oSo+xadK2U9OzCGbtYcq7M8yvPRA+oyncusOvKtk=,xoOOo+f2xCy85Zv23EABpPObHDyosh1r3e8SHM51AWc=,R5GJCbNjJnvSlwmKBEZXFfJeXm+OIVeZZUoD/wALi0M=,t/+v+VYPjKaNJnsaHPuWDkrUdhMKII5Rbm+aIo2UEkA=,Ayy00m7+d30EbFNDmVzHwPIyfKtPjRd1NCitoO0q3YI=,5ZW3WN6BsbBFXdQV9zKF3l0Tdf0LdIj9xloXVOQVeuM=,toYoOb+28/XGBPO6e9ewucgfvGLj+va8ARsqfk8Pnr8=,9hWkE4NkwY6joaruPOrCXnl8dSUFQmqiJlT4QDO2d88=,mU+jBAjTGz/aKZs5g+E17SRVPf0JLGnitVlJE6+Rzd8=,...,NdFjmzOsWUl44AUBAbYO3ukBG6Ivne7DeAq1CuSGcPc=,O0aA7jFW7AcqT7xnjC94c2Vh2yzda/3d9QHPeu8Kbgw=,fA7d5P46PhFxaMQgIEomxT0sqHlW8ZGQ51q2ftaHX8c=,d06OLwojOWXeuBQKqXVLNAwOfxzGnrhzut74+6Pyg98=,Daa5D/gGVWwTEwr3JKE/II2gF9PTaqoyjtO42hac8ws=,sMshmN+9A0JibTU23lFcU96AQrqGfGG7Yk4zX64zqdQ=,WMxcMfZXxhwn6RQmUvirPhI/sgLH4nDT+7v6t8QDf/U=,bDsYsdUvjjRNL0z8E2Za/VCQya2xBRnlkM+wkIihNqw=,8NSDfcnmriFQQhW6+64BWlMwKBgruQBE78ZY6im3eZA=,eW3ZkIoEUgVKHxUt1igZ0/3Gx3hk29HytX82zUomsJ8=
TransactionID,,,,,,,,,,,,,,,,,,,,,
3468513,7301121359774136185,5.864045e+14,582747479941197,9848624220811542,9.006340e+14,6.906556e+14,585081571241710,6.632375e+14,584498204459161,684188.0,...,614824775064230,684188.0,582747479941197,582747479941197,583331456802853,583331456802853,583914923844325,583331456802853,583914923844325,694157147562432

Sending encrypted input to http://134.226.86.101:8000/xgboost/ieee

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7f30d0fbe070>

Decrypted result: 0
Which is incorrect.
Time taken from encryption of input to decryption of result: 0 mins, 3 seconds, 602 ms