# Client Side

* Encrypt transaction data
* Send to server for inference
* Decrypt response

## XGBoost endpoint for ULB dataset

In [6]:
%run client.py --dataset=ulb --model=xgboost

ulb dataset loaded ✅..

Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
243632,152010.0,-0.837042,1.061457,-0.667447,-0.679083,0.839556,-0.620929,0.515868,0.355251,0.181275,...,-0.012742,-0.219203,-0.564756,-0.188678,0.311109,0.328596,-0.090378,-0.000017,-0.033123,23.45

Expected result: 0

Loading keys from ./client-files/encrypted-ulb-xgboost-keys.pt

Encrypted input:

,czebKLDJQhMNIYeCImYnpT3RpOTNcouhna83GH2EikA=,1LB2u3QUNLqLTGAHE5HhOIRDiEgOmjiOlsxY+pt/x8I=,3fq/Jj+i2e41xCl5D+SKbYQuJQXw/v3/peDD651luGA=,7oI7BRkwRDdFVEP+Y9tyxgYIuvxBfz4wvHEjo2EG/9M=,HGMc39lGxwOOy9gCBzx50qt/9SpJYxpx0BOUe/el0tM=,9z3oMmvj57D+0Oy/Bvbfs+L7uzJpjbnsk9C7oRZdzYM=,z2L/UIssLUJH4EfL4uj7gMYs5gO7IfEjIbU/VEpb1UY=,kFJKFHmWsT5kSVZxir/faVTARRmjXrWCzvMa7pHUCbQ=,AjBvhmjmV0ikU+SjANC1fgzfLLbONa45wI6SVrL6p/M=,4h6MMkxuYTnCIROrC5ezrhvBNC0Rf1uXQvOa3XuJgrg=,...,M4lVuGkM3WTOZ5zb93Xeqv8MNfDTXS/VP7Lff9QQZzQ=,jPQ5DyE+LAHDGa5iBhKBb71gQFwFMbrr25CQcoV835k=,c2rDuxq3lwmeJ9kkPgNi92+r5JvHRMnPvK7xgRd+MEk=,NaPZQwwKMW21sNYnDQ0yhMVJkzbKHqLf+cV9mDozipo=,vpRf3Igmy7gUf2ROngKCFUELOlBhVOK/cA2CUQg6EYI=,AJgpkzqQV1tA+mGNuCKHBMNvGYHowN8whRErDgCElS0=,fvU3zp28b5W8xB9Qwuqsu8jg5Oks+bvhsuyCbrCaA8U=,FlhcjP2mexBn8tuG1tyIMI5Zapjk1VzIA9fWNfMDZp8=,vdJ5Gcm7heE6I6pAHth+J/CXmD0Fj50ILJjWcaQIqJE=,G6e2H9GvGiUiHgfJJhz1CqZDK1yGpX0FSyqS2vgIktw=
243632,8.114789e+18,6.022411e+15,6.123683e+15,6.031459e+15,6.030838e+15,6.111850e+15,6.033942e+15,6.094586e+15,6.086016e+15,6.076733e+15,...,6.066387e+15,6.055373e+15,6.036936e+15,6.057002e+15,6.083660e+15,6.084594e+15,6.062247e+15,6.067066e+15,6.065301e+15,7.317874e+15

Sending encrypted input to http://134.226.86.101:8000/xgboost/ulb

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7f8a53092af0>

Decrypted result: 0
Which is correct!

## Ensuring selected transaction is fraudulant

In [8]:
%run client.py --dataset=ulb --model=xgboost --fraudulant

ieee dataset loaded ✅..

Test input:

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
3516558,13933326,14.386,0,5943,130.0,185.0,4,195.0,3,-999.0,...,58,-999.0,0,0,1,1,2,1,2,802

Expected result: 1

Loading keys from ./client-files/encrypted-ieee-xgboost-keys.pt

Encrypted input:

,ZZ0lBLLI278XHRzxEt6X0mWLTshn6/VfI5nwa4tdLpE=,qL+RGtdALHFBEqg29SWUdVD62C9D69zReAbc0ODFZ5s=,5GwSow8DeCKBTojhd59H7g2RfzUh/v3msRiJZbjpZa0=,/eOYIGtavWr5jfGSY2ImxLgyBoeccA3HP/pmCPJGWQM=,cQ8ute4l1SBVI5oAImnmzA95NWOh55gz47P2ULgZ4EE=,NjovCigVcPThZ45kHBgafYlH3adBv3Z2Io7/kv4aHZ8=,zzykcNrY0ZcErcJkfYjwhc7jps5IuXmkKzTc0l4m4z0=,a/RMgEJwIjPlhU2FzrIwAbQmjm9OXrk0peK7OUrNVUg=,0l8DjZNisjL739U7HEXnQjBCEjNVSIgV8hbKiFMiAPc=,k3REmmWSjV+xfsN14r7Vzuj8kcUKHWF0ZoY7OcmAWWg=,...,Q7xhwy5fRUc472PpxrqGEIAFSZX/omt06sKLe1Nct6s=,+yT1evfcWTCWgM2URXHz0qm06FN1o5OCdUbP7tXTJ6U=,DCE24lpCN/T9ryHpSrjlwzQRiB/rzferbKQBUz3Iyh4=,84sisL6Csev5q2hcG92F/T5o96cnC1eIna5hVsUzRAs=,Bh5S2Zm3ehzWgAuOsgxiiSDkM50VECbtnCWjQCIU2xA=,5lttQI1cEuECvhFiF/dDgWE3QMvUMiN2i1QLz1zUbjA=,0++89XpOhWyAaYgGa3zDjIOzbYyKxPJZsPik6NyZ37E=,N9nBts07W7B09UkPHv1p1R3dRwpNR4QYfAwUl03vdO4=,0ImRSFI3/jjWwixiUa69Rh9e/8D30jqUbT/ypZy6Pmk=,P0wHsfAOEVcqt9PPM2deDSMxS0/hFIBHU7AzxzzlPFk=
TransactionID,,,,,,,,,,,,,,,,,,,,,
3516558,8128029718184065488,5.911375e+14,582746420539645,4049390072692632,6.585713e+14,6.906536e+14,585079961235415,6.964842e+14,584496608359585,369657.0,...,616574248224802,369657.0,582746420539645,582746420539645,583329871561357,583329871561357,583913643324469,583329871561357,583913643324469,1050535521466502

Sending encrypted input to http://134.226.86.101:8000/xgboost/ieee

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7f8a500f3f10>

Decrypted result: 1
Which is correct!

## Neural Network endpoint for ULB Dataset

In [11]:
%run client.py --dataset=ulb --model=nn --fraudulant

ulb dataset loaded ✅..

Test input:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
275992,166831.0,-2.027135,-1.13189,-1.135194,1.086963,-0.010547,0.423797,3.79088,-1.155595,-0.063434,...,0.033804,-0.315105,0.57552,0.490842,0.756502,-0.142685,-0.602777,0.508712,-0.091646,634.3

Expected result: 1

Encrypted input:
<tenseal.tensors.ckksvector.CKKSVector object at 0x7f8a514b7460>

Sending encrypted input to http://134.226.86.101:8000/nn/ulb

Received encrypted result:
 <tenseal.tensors.ckksvector.CKKSVector object at 0x7f8a514b7a60>

Decrypted result: 0
Which is incorrect.

## XGBoost endpoint for IEEE dataset

In [2]:
%run client.py --dataset=ieee --model=xgboost --fraudulant

ieee dataset loaded ✅..

Test input:

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
3518304,13987724,59.636,0,15944,266.0,185.0,3,137.0,2,-999.0,...,99,-999.0,0,0,1,1,1,1,2,0

Expected result: 1

Loading keys from ./client-files/encrypted-ieee-xgboost-keys.pt

Encrypted input:

,ZZ0lBLLI278XHRzxEt6X0mWLTshn6/VfI5nwa4tdLpE=,qL+RGtdALHFBEqg29SWUdVD62C9D69zReAbc0ODFZ5s=,5GwSow8DeCKBTojhd59H7g2RfzUh/v3msRiJZbjpZa0=,/eOYIGtavWr5jfGSY2ImxLgyBoeccA3HP/pmCPJGWQM=,cQ8ute4l1SBVI5oAImnmzA95NWOh55gz47P2ULgZ4EE=,NjovCigVcPThZ45kHBgafYlH3adBv3Z2Io7/kv4aHZ8=,zzykcNrY0ZcErcJkfYjwhc7jps5IuXmkKzTc0l4m4z0=,a/RMgEJwIjPlhU2FzrIwAbQmjm9OXrk0peK7OUrNVUg=,0l8DjZNisjL739U7HEXnQjBCEjNVSIgV8hbKiFMiAPc=,k3REmmWSjV+xfsN14r7Vzuj8kcUKHWF0ZoY7OcmAWWg=,...,Q7xhwy5fRUc472PpxrqGEIAFSZX/omt06sKLe1Nct6s=,+yT1evfcWTCWgM2URXHz0qm06FN1o5OCdUbP7tXTJ6U=,DCE24lpCN/T9ryHpSrjlwzQRiB/rzferbKQBUz3Iyh4=,84sisL6Csev5q2hcG92F/T5o96cnC1eIna5hVsUzRAs=,Bh5S2Zm3ehzWgAuOsgxiiSDkM50VECbtnCWjQCIU2xA=,5lttQI1cEuECvhFiF/dDgWE3QMvUMiN2i1QLz1zUbjA=,0++89XpOhWyAaYgGa3zDjIOzbYyKxPJZsPik6NyZ37E=,N9nBts07W7B09UkPHv1p1R3dRwpNR4QYfAwUl03vdO4=,0ImRSFI3/jjWwixiUa69Rh9e/8D30jqUbT/ypZy6Pmk=,P0wHsfAOEVcqt9PPM2deDSMxS0/hFIBHU7AzxzzlPFk=
TransactionID,,,,,,,,,,,,,,,,,,,,,
3518304,8159760555835573650,6.175271e+14,582746420539645,9882898830610321,7.379032e+14,6.906536e+14,584496608359585,6.626528e+14,583913643324469,369657.0,...,640490589697039,369657.0,582746420539645,582746420539645,583329871561357,583329871561357,583329871561357,583329871561357,583913643324469,582746420539645

Sending encrypted input to http://134.226.86.101:8000/xgboost/ieee

Received encrypted result:
 <phe.paillier.EncryptedNumber object at 0x7fda3db56b50>

Decrypted result: 1
Which is correct!